trigger:
- none
 
parameters:
- name: environment
  type: object
  default:
  - name: 'dev'
    k8_Service_Connection: "REPLACE_WITH_YOUR_K8_SERVICE_CONNECTION" # Service connection to your AKS Cluster
    cluster_name: "REPLACE_WITH_YOUR_CLUSTER_NAME" # This will be cluster name that you will see on prisma cloud console. Please give a proper name
    cluster_without_twistlock_namespace: false # Set to TRUE If twistlock namespace doesnt exists on your aks cluster
 
pool:
vmImage: 'ubuntu-latest'
 
steps:
- ${{ each env in parameters.environment }}:
  - checkout: git://APP-9001 Shared Technical Platforms and Components/prisma-defender
  - script: |
      sed -i -e "s/REPLACE_WITH_CLUSTER_NAME/${{ env.cluster_name }}/g" defender/defender-AKS-CRI.yaml 
  - ${{ if eq(env.cluster_without_twistlock_namespace, true) }}:
    - task: Kubernetes@1
       displayName: Create Namespace Twistlock
       inputs:
         connectionType: 'Kubernetes Service Connection'
         kubernetesServiceEndpoint: ${{ env.k8_Service_Connection }}
         command: 'create'
         arguments: 'namespace twistlock'
 
  - task: KubernetesManifest@0
    displayName: Deploy Twistlock Manifests
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: ${{ env.k8_Service_Connection }}
      namespace: 'twistlock'
      manifests: 'defender/defender-AKS-CRI.yaml'